name: cadvisor
services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    privileged: true
    container_name: cadvisor
    restart: unless-stopped
    ports:
      - 9323:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /cgroup/cpu:/cgroup/cpu
      - /cgroup/cpuacct:/cgroup/cpuacct
      - /cgroup/cpuset:/cgroup/cpuset
      - /cgroup/memory:/cgroup/memory
      - /cgroup/blkio:/cgroup/blkio
