volumes:
  n8n_data:

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=n8n.ehcan.io
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://n8n.ehcan.io
      - GENERIC_TIMEZONE=Europe/Berlin
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_PUBLIC_API_SWAGGERUI_DISABLED=true
      - N8N_PROXY_HOPS=1
    volumes:
      - n8n_data:/home/node/.n8n
