volumes:
  n8n_data:
  redis_data:

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=n8n.lab.ehcan.io
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://n8n.lab.ehcan.io
      - GENERIC_TIMEZONE=Europe/Berlin
      - N8N_PUBLIC_API_SWAGGERUI_DISABLED=true
      - N8N_PROXY_HOPS=1
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_VERSION_NOTIFICATIONS_ENABLED=false
      - N8N_TEMPLATES_ENABLED=false
      - EXTERNAL_FRONTEND_HOOKS_URLS=""
      - N8N_DIAGNOSTICS_CONFIG_FRONTEND=""
      - N8N_DIAGNOSTICS_CONFIG_BACKEND=""
      - N8N_METRICS=true
      - QUEUE_HEALTH_CHECK_ACTIVE=true
      - NODES_EXCLUDE="[]"
      - N8N_RUNNERS_ENABLED=true
      - N8N_RUNNERS_MODE=external
      - N8N_RUNNERS_BROKER_LISTEN_ADDRESS=0.0.0.0
      - N8N_RUNNERS_AUTH_TOKEN=${N8N_RUNNERS_AUTH_TOKEN}
      # Custom Environment Variables
      - CUSTOM_MNLR_SECRET=${CUSTOM_MNLR_SECRET}
    volumes:
      - n8n_data:/home/node/.n8n
    extra_hosts:
    - "docker-host:192.168.2.102"
  task-runners:
    image: n8nio/runners
    container_name: n8n-runners
    environment:
      - N8N_RUNNERS_TASK_BROKER_URI=http://n8n:5679
      - N8N_RUNNERS_AUTH_TOKEN=${N8N_RUNNERS_AUTH_TOKEN}
      # Custom Environment Variables
      - CUSTOM_MNLR_SECRET=${CUSTOM_MNLR_SECRET}
    depends_on:
      - n8n
  redis:
    image: redis:latest
    container_name: n8n-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
