name: notion-telegram-event-reminder

services:
  notion-telegram-event-reminder:
    image: ghcr.io/ehcaning/notion-telegram-event-reminder:latest
    container_name: notion-telegram-event-reminder
    environment:
      NOTION_TOKEN: ${NOTION_TOKEN}
      NOTION_DATABASE_ID: ${NOTION_DATABASE_ID}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
      TELEGRAM_MESSAGE_THREAD_ID: ${TELEGRAM_MESSAGE_THREAD_ID}
      DEBUG: ${DEBUG}
      CRON: ${CRON}
      TIMEZONE: ${TIMEZONE}
    restart: unless-stopped
