name: TG File Stream Bot

services:
  fsb-run:
    image: ghcr.io/everythingsuckz/fsb
    container_name: fsb
    restart: unless-stopped
    ports:
      - "8038:8038"
    environment:
      - API_ID
      - API_HASH
      - BOT_TOKEN
      - LOG_CHANNEL
      - ALLOWED_USERS
      - PORT=8038
      - HOST=http://192.168.2.102:8038
