name: nginx-proxy-manager
services:
  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    network_mode: host
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    environment:
      DB_SQLITE_FILE: '/data/database.sqlite'
      DISABLE_IPV6: 'true'
    volumes:
      - /data/nginx-proxy-manager/data:/data
      - /data/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
